### ISSUE TITLE
How to set video parameters？

### ISSUE THREAD

**Issue by jackweiwang** [davidstutz/hierarchical-graph-based-video-segmentation#1]
I want to read the 01.MP4

![image](https://cloud.githubusercontent.com/assets/19305790/25113740/255fce00-242c-11e7-9f25-30354acbaea9.png)

this error how to resolve ？

thanks

**Comment by davidstutz** [comment]
The code does not support to directly load an MP$ file. Use FFMPEG to convert the MP4 file to a set of images first. Then you can apply the command line tool.
